### ISSUE TITLE
DOC: readme & contributing documents

### ISSUE THREAD

**Issue by sndpgm** [sndpgm/lpmd#5]
- [x] initial version of README.md (#7)
- [x] initial version of CONTRIBUTING.md (#22)
- [x] cleanup README.md & CONTRIBUTING.md (#22)
